#!/usr/bin/env zsh
# Copyright 2018 Jamiel Almeida
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

typeset target_file="${HOME}/.config/i3/config"

typeset this_dir="${${(%):-%x}:A:h}"
typeset -aU basedirs=()

typeset basedir=''
for basedir in "${(s.:.)HOME_REPOS}"; do
    [[ ! -d "${basedir}/.config/i3" ]] || basedirs+=( "${basedir}/.config/i3" )
    [[ ! -d "${basedir}/i3" ]] || basedirs+=( "${basedir}/i3" )
done

basedirs+=(
    "${target_file:A:h}"
    "${target_file:a:h}"
    "${this_dir:h:h}"
)

mkdir --verbose --parents --mode='u=rwx,go=' "${target_file:h}"
assemble-config -v -b -V i3 -f "${target_file}" "${(@)basedirs}"
