#!/usr/bin/env bash
# Copyright 2018 Jamiel Almeida
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# open the last log for i3 with less

typeset LAST_LOGFILE="$(
    find "${HOME}/.local/log" -name 'i3-*.log' | sort | tail -n1
)"
if [[ -z "${LAST_LOGFILE:-}" ]]; then
    echo "No logs to tail" >&2
    exit 1
fi
exec less -N +G "${LAST_LOGFILE}"
