#!/usr/bin/env bash
# Copyright 2018 Jamiel Almeida
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Block that shows if we can reach a 20X http status code from "the internet"
# and highlights accordingly.

set -eu -o pipefail

if ! command -v 200 >/dev/null 2>&1; then
    exit
fi

typeset STATUS='OFFLINE'
typeset COLOR='#BF5D5A'

if 200 -n; then
    STATUS='ONLINE'
    COLOR='#A1B56C'
fi
printf "%s\n%s\n%s\n" "${STATUS}" "${STATUS}" "${COLOR}"
