#!/usr/bin/env zsh
# Copyright 2018 Jamiel Almeida
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Block that shows loadavg, and highlights when load for 1min surpasses
# (numerically) the number of cores in the system.

typeset -i10 processors="$(nproc)"

typeset -F 2 load1=0.00
typeset -F 2 load5=0.00
typeset -F 2 load15=0.00
typeset runnin=''
typeset -i10 last_pid=0
read -r load1 load5 load15 running last_pid </proc/loadavg

printf "%.2f %.2f %.2f\n%.2f\n" "${load1}" "${load5}" "${load15}" "${load1}"
[[ "${processors}" -gt "${load1}" ]] || echo '#BF5D5A'
