#!/usr/bin/env bash
# Copyright 2018 Jamiel Almeida
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Block that shows a plug icon if the AC adapter is plugged in for the
# specified adapter (defaults to 0). Line 20 can be commented out to show the
# word 'unplugged' in yellow if desired.

set -eu -o pipefail

typeset ADAPTER_NUM="${BLOCK_INSTANCE:-0}"
typeset TEXT='unknown'
typeset COLOR='#BF5D5A'

if ! command -v acpi >/dev/null 2>&1; then
    exit
fi

typeset ACPI_OUTPUT="$(acpi -a)"

if grep -qE " ${ADAPTER_NUM}: on-line" <<<"${ACPI_OUTPUT}"; then
    TEXT=$'\uf1e6'
    COLOR='#A1B56C'
elif grep -qE " ${ADAPTER_NUM}: off-line" <<<"${ACPI_OUTPUT}"; then
    TEXT='unplugged'
    COLOR='#DBA656'
    exit
fi

printf "%s\n%s\n%s\n" "${TEXT}" "${TEXT}" "${COLOR}"
