#!/usr/bin/env python
# Copyright 2018 Jamiel Almeida
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Shows all the importable python files within a series of directories
"""

import collections
import sys
import pprint

from glob import glob
from os.path import join, isdir, isfile

UNWANTED_DIR_NAMES = [
    '/_vendor',
    '/test',
    '/tests',
    '_test',
    '_tests',
]

def importable_files(root_directory):
    directories = collections.deque()
    directories.append(root_directory)

    while directories:
        directory = directories.popleft()
        dir_contents = glob(join(directory, '*'))
        for child in dir_contents:
            if isdir(child) and isfile(join(child, '__init__.py')):
                matches = [child.endswith(pat) for pat in UNWANTED_DIR_NAMES]
                if not any(matches):
                    directories.append(child)
            elif isfile(child) and child.endswith('.py'):
                yield child

if __name__ == '__main__':
    target_dirs = sys.argv[1:]
    for directory in target_dirs:
        for pyfile in importable_files(directory):
            print(pyfile)
