#!/usr/bin/env zsh
# Copyright 2018 Jamiel Almeida
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Show's the a given python executable's sys.path directories

setopt err_exit
setopt extended_glob
setopt no_unset
setopt pipe_fail

typeset PYTHON_INTERP="${${1:-python}:c}"
typeset PYTHON_CUSTOMSITE="${2:-${PYTHON_CUSTOMSITE:-}}"

typeset -gxTU PYTHONPATH pythonpath ':'
if [[ -d "${PYTHON_CUSTOMSITE}" ]]; then
    pythonpath=( "${PYTHON_CUSTOMSITE:a}" "${(@)pythonpath}" )
fi
exec ${PYTHON_INTERP} <<-EOSCRIPT
import sys, site
from collections import OrderedDict as OD
from os.path import isdir, realpath

path_elem = OD([(realpath(rp), 1,) for rp in sys.path if isdir(rp)]).keys()
print('\n'.join(path_elem))
EOSCRIPT
