#!/usr/bin/env bash
# Copyright 2018 Jamiel Almeida
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu -o pipefail
if [[ "${IM_SURE-no}" != 'yes' ]]; then
    echo -n $'\x1b[0m\x1b[1;31m'
    echo "To proceed with this you should set IM_SURE=yes" >&2
    echo "" >&2
    echo "This script deletes, irrevocably, a lot of stuff" >&2
    echo "in the current directory." >&2
    echo "" >&2
    echo "Read the source and make surethis is exactly" >&2
    echo " what you want to do." >&2
    echo "" >&2
    echo "Example command:" >&2
    echo $'\t'"IM_SURE=yes ${0}" >&2
    echo -n $'\x1b[0m'
    exit 1
fi
cd "$(command realpath -s "$(dirname "${0}")")"
find ./ -mindepth 1 -maxdepth 1 \
    '(' -name '.*' -o -name '_*' ')' \
    -exec rm -rvf '{}' '+'
