#!/usr/bin/env zsh
# Copyright 2018 Jamiel Almeida
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# If no ssh-agent is attached to this TMUX session, launch one and attach to it

setopt err_exit
setopt no_unset
setopt pipe_fail
setopt xtrace

[[ -n "${TMUX:-}" ]] || exit 1

eval "$(tmux show-environment -s)"

[[ ! -S "${SSH_AUTH_SOCK:-}" ]] || exit 1
[[ -z "${SSH_AUTH_SOCK:-}${SSH_CONNECTION:-}" ]] || exit 1

eval "$("${${:-ssh-agent}:c}" 2>/dev/null)"
tmux set-environment SSH_AGENT_PID "${SSH_AGENT_PID}"
tmux set-environment SSH_AUTH_SOCK "${SSH_AUTH_SOCK}"
