#!/usr/bin/env zsh
# Copyright 2018 Jamiel Almeida
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# If present, make tmux source host-specific or local-only configuration files.

setopt err_exit
setopt no_unset
setopt pipe_fail

[[ -n "${TMUX:-}" ]] || exit 1

typeset TMUX_CONF_DIR="${TMUX_CONF_DIR:-${${:-${HOME}/.tmux.conf}:A:h}}"
typeset SHORT_HOST="$(hostname)"
typeset LONG_HOST="$(hostname -f)"
typeset -a POTENTIAL_CONFIGS=(
    "${TMUX_CONF_DIR}/host-specific/${SHORT_HOST}.conf"
    "${TMUX_CONF_DIR}/host-specific/${LONG_HOST}.conf"
    "${HOME}/.tmux.conf.local"
    "${HOME}/.tmux/tmux.conf.local"
)

which tmux-theme >/dev/null 2>&1 && \
    THEME_GLOBAL=yes tmux-theme

for CONFIG_FILE in "${(@)POTENTIAL_CONFIGS}"; do
    [[ ! -f "${CONFIG_FILE}" ]] || \
        tmux source-file "${CONFIG_FILE}"
done
unset POTENTIAL_CONFIGS
