#!/usr/bin/env zsh
# Copyright 2018 Jamiel Almeida
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Widget that shows GREEN(good)/RED(bad) depending on whether the current host
# is able to access the internet
#
# This is done by ensuring the output is a string with the proper message
# format for tmux. And cause that string to be appended to the status line.

setopt err_exit
setopt no_unset
setopt pipe_fail

[[ -e "${HOME}/.local/tmux-widget-internet.enable" ]] || exit 0
command -v 200 >/dev/null 2>&1 || exit 1

if [[ "${1:-}" == "--nofancy" ]]; then
    FANCY=n
else
    FANCY=y
fi
if 200 -n; then
    [[ "${FANCY}" == "n" ]] || \
        echo -n "#[fg=colour002,bg=colour242,nobold,nounderscore,noitalics]"
    echo "#[fg=colour233,bg=colour002,bold]  ONLINE "
else
    [[ "${FANCY}" == "n" ]] || \
        echo -n "#[fg=colour001,bg=colour242,nobold,nounderscore,noitalics]"
    echo "#[fg=colour253,bg=colour001,bold] OFFLINE "
fi
