#!/usr/bin/env zsh
# Copyright 2018 Jamiel Almeida
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Switch between C-Space and C-o TMUX leader prefixes, this is useful when
# nesting tmux sessions, or opening tmux sessions on a remote host while
# keeping a session locally.

setopt err_exit
setopt no_unset
setopt pipe_fail

[[ -n "${TMUX:-}" ]] || exit 1

current-leader () {
    local prefix
    prefix="$(tmux show-option -v prefix)"
    if [[ -z "${prefix:-}" ]]; then
        prefix="$(tmux show-option -gv prefix)"
    fi
    echo "${prefix:-C-Space}"
}

typeset CURRENT_LEADER="$(current-leader)"
typeset NEW_LEADER='Space'
typeset OTHER_LEADER='o'
if [[ "${CURRENT_LEADER}" == "C-Space" ]]; then
    NEW_LEADER='o'
    OTHER_LEADER='Space'
fi

tmux set-option prefix "C-${NEW_LEADER}"
tmux bind-key "C-${NEW_LEADER}" send-prefix
tmux bind-key "${NEW_LEADER}" last-window
tmux bind-key "C-${OTHER_LEADER}" clock-mode

tmux display-message "tmux leader set to: $(current-leader)"
