#!/usr/bin/env zsh
# Copyright 2018 Jamiel Almeida
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

exec </dev/null
exec >/dev/null
exec 2>/dev/null

typeset PROFILE="${BROWSER_WORK_PROFILE:-}"
typeset -a browser_cmd=( "${BROWSER}" )

if [[ -n "${PROFILE}" ]]; then
    case "${BROWSER}" in
        *chrom*) browser_cmd+=( --profile-directory="${PROFILE}" );;
        *) browser_cmd+=( --profile "${PROFILE}" );;
    esac
fi
[[ "${#}" -eq 1 ]] || exit

case "${BROWSER}" in
    *chrom*) browser_cmd+=( --app="${1}" );;
    *) browser_cmd+=( "${1}" );;
esac

exec "${(@)browser_cmd}" & disown
