#!/usr/bin/env python3
# Copyright 2018 Jamiel Almeida
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Simple script to show how 256colors look on the current terminal using ANSI
escape codes
"""

NUMBER_TEMPLATE = (
  "\x1b[0m {number:03d}: \x1b"
  "[{prefix}{number:03d}mSam\x1b[7mple\x1b[0m"
)

def cstring(color_number, prefix='38;5;'):
    return NUMBER_TEMPLATE.format(prefix=prefix, number=color_number)

if __name__ == '__main__':

  for i in range(16, 232 - 6, 36):
    for j in range(6):
      print( *[cstring(i+j+k*6) for k in range(6)] )

  print()
  for i in range(0, 8):
    print(
      cstring(i), cstring(i+8),
      " "*12,
      cstring(232+i*3), cstring(232+i*3+1), cstring(232+i*3+2)
    )
