#!/usr/bin/env zsh
# Copyright 2018 Jamiel Almeida
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

typeset DATABASE_FILE="${HOME}/Cloud/Personal/PasswordDatabase.kdbx"
typeset KEY_FILE="${HOME}/Cloud/Personal/PasswordDatabase.key"

if [[ ! -r "${DATABASE_FILE}" ]] || [[ ! -r "${KEY_FILE}" ]]; then
    exit 1
fi

exec keepassxc --keyfile="${KEY_FILE}" "${DATABASE_FILE}"
