#!/usr/bin/env bash
# Copyright 2018 Jamiel Almeida
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu -o pipefail

cd "$(command realpath -s "$(dirname "${0}")")"

typeset -a spellfile_urls=(
    'http://ftp.vim.org/pub/vim/runtime/spell/en.utf-8.spl'
    'http://ftp.vim.org/pub/vim/runtime/spell/en.utf-8.sug'
    'http://ftp.vim.org/pub/vim/runtime/spell/es.utf-8.spl'
    'http://ftp.vim.org/pub/vim/runtime/spell/es.utf-8.sug'
)

for url in "${spellfile_urls[@]}"; do
    [[ ! -f "./$(basename ${url})" ]] || \
        rm -vf "./$(basename ${url})"
    curl -o "./$(basename ${url})" "${url}" &
done
wait
