#!/usr/bin/env zsh
# Copyright 2018 Jamiel Almeida
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# i3 commands to execute after successfully loading the base configuration for
# hosts that do not have a script for specific commands

i3-msg '
    workspace --no-auto-back-and-forth number 1;
    rename workspace to "1:  Terms     ";
    move workspace to output primary;
    exec --no-startup-id my-sensible-terminal
'
