#!/usr/bin/env bash
# Copyright 2018 Jamiel Almeida
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Send stuff to the clipper unix socket using a temporary file as a buffer.
#
# This is intended for a quick-but-maybe-not-instantaneous clipboard command
# run to protect against socket timeouts.

test -S "${HOME}/.ssh/sock/clipper.sock" || exit 1

mkdir --verbose --parents --mode='u=rwx,go=' "${HOME}/.local/clipboard"
typeset TMP_CLIPBOARD_FILE="$(mktemp --tmpdir="${HOME}/.local/clipboard")"

cleanup () {
    rm -f "${TMP_CLIPBOARD_FILE}"
}

trap cleanup EXIT ERR QUIT

cat > "${TMP_CLIPBOARD_FILE}"

exec nc -w1 -q0 -U "${HOME}/.ssh/sock/clipper.sock" <"${TMP_CLIPBOARD_FILE}"
