#!/usr/bin/env bash
# Copyright 2018 Jamiel Almeida
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Kill clipper, remove the socket. If there are command line args, ssh to the
# remote hosts and run clipper-rm instead of locally.

set -eu -o pipefail
if [[ "${#}" -eq 0 ]]; then
    pkill -u "${USER}" -x clipper
    rm -vf "${HOME}/.ssh/sock/clipper.sock"
    exit 0
fi

while [[ "${#}" -ge 1 ]]; do
    echo "running clipper-rm on ${1?}..."
    ssh "${1?}" clipper-rm
    shift
done
