#!/usr/bin/env bash
# Copyright 2018 Jamiel Almeida
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Start a clipper process if not running, and clean up/restart if using -f

set -eu -o pipefail
if [[ "${1:-}" == '-f' ]]; then
    clipper-rm
fi
if [[ -e "${HOME}/.ssh/sock/clipper.sock" ]]; then
    echo "Error: Sock file at '${HOME}/.ssh/sock/clipper.sock' exists." >&2
    exit 1
fi
clipper &
disown
